"""empty message

Revision ID: 062159f6d653
Revises: 3e40d5a1ab9b
Create Date: 2020-04-11 14:23:05.378356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '062159f6d653'
down_revision = '3e40d5a1ab9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('director_first_name_key', 'director', type_='unique')
    op.drop_constraint('director_last_name_key', 'director', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('director_last_name_key', 'director', ['last_name'])
    op.create_unique_constraint('director_first_name_key', 'director', ['first_name'])
    # ### end Alembic commands ###
