"""empty message

Revision ID: 5c9117a32c49
Revises: 062159f6d653
Create Date: 2020-04-11 14:23:52.803408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c9117a32c49'
down_revision = '062159f6d653'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cast_member_first_name_key', 'cast_member', type_='unique')
    op.drop_constraint('cast_member_last_name_key', 'cast_member', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('cast_member_last_name_key', 'cast_member', ['last_name'])
    op.create_unique_constraint('cast_member_first_name_key', 'cast_member', ['first_name'])
    # ### end Alembic commands ###
