"""empty message

Revision ID: 94454da7206c
Revises: 25500a9e3f03
Create Date: 2020-04-11 13:51:21.667608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94454da7206c'
down_revision = '25500a9e3f03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('plot', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'plot')
    # ### end Alembic commands ###
